dist: bionic
os: linux
language: generic
env:
  global:
    - PATH=/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH
before_install:
  - wget https://github.com/nxadm/rakudo-pkg/releases/download/v2019.11/rakudo-pkg-Ubuntu18.04_2019.11-01_amd64.deb
  - sudo dpkg -i rakudo-pkg-Ubuntu18.04_2019.11-01_amd64.deb
  - wget 'http://http.us.debian.org/debian/pool/main/g/gsl/libgslcblas0_2.5+dfsg-6_amd64.deb'
  - wget 'http://http.us.debian.org/debian/pool/main/g/gsl/libgsl23_2.5+dfsg-6_amd64.deb'
  - sudo dpkg -i libgslcblas0_2.5+dfsg-6_amd64.deb libgsl23_2.5+dfsg-6_amd64.deb
install:
  - zef install --deps-only --/test .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/*.rakutest
